project: 
  type: website
  output-dir: docs

website:
  title: "My Data Analysis Portfolio"
  navbar:
    left:
      - text: "About Me"
        href: ./aboutme.html
      - text: "Projects"
        menu:
          - text: "R Coding Exercise"
            href: ./exercise/code/analysis_code/coding_exercise.html
          - text: "Data Analysis Exercise"
            href: ./exercise/code/data_processing_code/dataanalysis_exercise.html
          - text: "Visualization Exercise"
            href: ./exercise/code/analysis_code/visualization_exercise.html
          - text: "Tidy Tuesday Exercise"
            href: ./exercise/code/analysis_code/tidytuesday_exercise.html
          - text: "Tidy Tuesday 2 Exercise"
            href: ./exercise/code/analysis_code/tidytuesday_exercise2.html  
      - text: "fluanalysis"
        menu:
          - text: "wrangling"
            href: ./fluanalysis/code/wrangling.html
          - text: "exploration"
            href: ./fluanalysis/code/exploration.html
          - text: "fitting"
            href: ./fluanalysis/code/fitting.html
          - text: "Model evaluation"
            href: ./fluanalysis/code/modeleval.html
          - text: "Machine Learning"
            href: ./fluanalysis/code/machinelearning.html
    right:
      - icon: github 
        href: "https://github.com/Weifanwu66/Weifan-MADA-portfolio"
format:
  html:
    theme: cosmo
    highlight: zenburn
    css: styles.css
    toc: FALSE


