---
title: "R Coding Exercise"
output:
  html_document:
    toc: FALSE
---

loading and checking data

```{r}
#load dslabs package
library("dslabs")
#load tidyverse package
library("tidyverse")
#get an overview of data structure
str(gapminder)
#get a summary of data structure
summary(gapminder)
#determine type of objective gapminder is
class(gapminder)
```

processing data

```{r}
#assign African countries to a new object
africadata=filter(gapminder,continent=="Africa")
#get an overview of data structure of africadata
str(africadata)
#get a summary of data structure
summary(africadata)
#create a data frame that only contains infant_mortality and life_expectancy from africadata
infant_mortality_longevity=select(africadata,infant_mortality,life_expectancy)
#create a data frame that only contains population and life_expectancy
pop_longevity=select(africadata,population,life_expectancy)
#create a data frame that only contains infant_mortality and life_expectancy from africadata
infant_mortality_longevity=select(africadata,infant_mortality,life_expectancy)
#create a data frame that only contains population and life_expectancy
pop_longevity=select(africadata,population,life_expectancy)
```

plotting

```{r}

#plot life expectancy as a function of infant mortality
ggplot(data=infant_mortality_longevity)+
geom_point(mapping=aes(x=infant_mortality,y=life_expectancy),color="blue")+
  labs(title="life expectancy and infant mortality",x="infant mortality",y="life expectancy")+
  theme_minimal()
#plot life expectancy as a function of population size
ggplot(data=pop_longevity)+
  geom_point(mapping=aes(x=population, y=life_expectancy),color="green")+
  scale_x_log10()+
  labs(title="life expectancy and infant mortality",x="infant_mortality",y="life expectancy")+
  theme_minimal()

```

```{r}
#filter out the year without missing values and create a data frame contains the year and count
dataframe=filter(africadata,is.na(infant_mortality))%>%
  group_by(year)%>%
  count(year)
dataframe
#create a new data frame containg the data for the year 2000
year2000=filter(africadata,year==2000)
#get a overview of new data frame year2000
str(year2000)
#get a summary of year2000
summary(year2000)
```


```{r}
#plotting the relationship between life expectancy and infant mortality for year 2000
year2000%>%
  ggplot()+
  geom_point(aes(y=life_expectancy,x=infant_mortality),color="blue")+
  labs(x="infant mortality", y="life expectancy", title="relationship between infant mortality and life expectancy")+
  theme_minimal()
#plotting the relationship between life expectancy and population size for year 2000
year2000%>%
  ggplot()+
  geom_point(aes(y=life_expectancy,x=population),color="green",alpha=0.5)+
  scale_x_log10()+
  labs(x="population size on log scale",y="life expectancy", title="relationship between life expectancy and populaton size")+
  theme_minimal()
```

build a linear regression model to predict life expectancy

```{r}
#build a linear model using lm function and fit life expectancy as outcome, and infant mortality as the predictor
lm1=lm(life_expectancy~infant_mortality,data=year2000)
#summary of linear regression model 1
summary(lm1)
#build a linear model using lm function and fit life expectancy as outcome, and population size as the predictor
lm2=lm(life_expectancy~population,data=year2000)
#summary of linear regression model 1
broom::tidy(lm2,conf.int=TRUE)%>%
  knitr::kable(digits=3)

```

based on the p_value for each fit, we can see that infant mortality can significantly predict life expectancy whereas population size can not predict the life expectancy

-----------------------------------------------------------------------------------------------------------------------
                                                           Aidan Troha Edits
```{r}
# Creates a new data frame which removes rows without reported gdp data &
# groups based on region
africa_GDP <- africadata %>%
                 filter(!(is.na(gdp))) %>%
                 group_by(region)

# Plots a "LOESS" model predicting log-scale GDP over time by region
ggplot(africa_GDP,aes(x=year,y=log(gdp),color=region,fill=region)) +
   geom_smooth(alpha=0.15) +
   labs(y="Log scale GDP",title="GDP Growth Over 50 Year Period by Region")
```
```{r}
# Plots a violin plot displaying the distribution of life expectancies
# according to region
ggplot(aes(region,life_expectancy,fill=region),data=africa_GDP)+
          geom_violin() +
          scale_x_discrete(labels = NULL, breaks = NULL) +
          labs(x=NULL,y="Life Expectancy",title="Life Expectancy Distributed by Region")
```
```{r}
# Fits a linear regression model using log-scale gdp to predict life expectancy
lm3 <- lm(life_expectancy~log(gdp),data=africa_GDP)

#summary of linear regression model 3
summary(lm3)
```